FROM python:3.7-alpine
COPY . /app
WORKDIR /app
RUN pip install .
RUN face_server create-db
RUN face_server populate-db
RUN face_server add-user -u admin -p admin
EXPOSE 5000
CMD ["face_server", "run"]
